{% set name = "egobox" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17f5c73d41c4afb0f171353f09af90bcf137af9ea37a91fdf2d9108037670d4c

build:
  skip: true  # [py<38 or python_impl == 'pypy']
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python

test:
  imports:
    - egobox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/relf/egobox
  summary: a Rust toolbox for efficient global optimization
  license: Apache-2.0
  license_family: Apache
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - relf
