{% set name = "egobox" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9bac83122334c9519912d4adfafd653a29d91acf9669d3c747cb55489b424a4

build:
  skip: true  # [py<38 or python_impl == 'pypy']
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [ build_platform != target_platform ]
    - cross-python_{{ target_platform }}     # [ build_platform != target_platform ]
    - crossenv                               # [ build_platform != target_platform ]
    - maturin >=1.4,<2.0                     # [ build_platform != target_platform ]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python

test:
  imports:
    - egobox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/relf/egobox
  summary: a Rust toolbox for efficient global optimization
  license: Apache-2.0
  license_family: Apache
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - relf
